apiVersion: 1

datasources:
  - name: Self-Healing-DB-V2
    type: postgres
    uid: postgres-self-healing-v2
    url: postgres:5432
    user: ${POSTGRES_USER}
    database: self_healing
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: false
    editable: true
