#!/bin/bash
# scripts/sync-secrets-gcp.sh
# Syncs GCP Secret Manager secrets to a local .env file
# (Maps lowercase terraform secret names to uppercase ENV names)

OUTPUT_FILE=".env"
TEMP_FILE=".env.tmp"

# Mapping: GCP_SECRET_NAME:ENV_VAR_NAME
MAPPINGS=(
    "postgres_password:POSTGRES_PASSWORD"
    "redis_password:REDIS_PASSWORD"
    "chatwoot_secret_key_base:CHATWOOT_SECRET_KEY_BASE"
    "chatwoot_api_token:CHATWOOT_API_TOKEN"
    "dify_secret_key:DIFY_SECRET_KEY"
    "dify_sandbox_api_key:DIFY_SANDBOX_API_KEY"
    "evolution_authentication_api_key:EVOLUTION_AUTHENTICATION_API_KEY"
    "handoff_shared_secret:HANDOFF_SHARED_SECRET"
    "grafana_admin_password:GRAFANA_ADMIN_PASSWORD"
    "cloudflare_api_token:CLOUDFLARE_API_TOKEN"
)

echo "Fetching secrets from GCP Secret Manager..."

# Start with a fresh temp file
echo "# Generated by scripts/sync-secrets-gcp.sh on $(date)" > "$TEMP_FILE"

for mapping in "${MAPPINGS[@]}"; do
    IFS=":" read -r secret env_var <<< "$mapping"
    
    echo "Syncing $secret -> $env_var..."
    # Access the latest version of the secret
    value=$(gcloud secrets versions access latest --secret="$secret" 2>/dev/null)
    
    if [ $? -eq 0 ]; then
        echo "$env_var=$value" >> "$TEMP_FILE"
    else
        echo "Warning: Failed to fetch secret '$secret'. Is it created in GCP?"
    fi
done

# Check if we should merge with existing .env
if [ -f "$OUTPUT_FILE" ]; then
    echo "Merging with existing $OUTPUT_FILE..."
    # Simple merge: Append unique lines or overwrite?
    # For a robust approach, we'd use sed/awk, but here we overwrite for SSOT.
    cp "$TEMP_FILE" "$OUTPUT_FILE"
else
    mv "$TEMP_FILE" "$OUTPUT_FILE"
fi

rm -f "$TEMP_FILE"
echo "Sync complete."
