#!/bin/bash
# scripts/sync-secrets-gcp.sh
# Syncs GCP Secret Manager secrets to a local .env file

OUTPUT_FILE=".env"
TEMP_FILE=".env.tmp"

# List of secrets to fetch (comma-separated or from a list)
SECRETS=(
    "POSTGRES_PASSWORD"
    "REDIS_PASSWORD"
    "CHATWOOT_SECRET_KEY_BASE"
    "DIFY_SECRET_KEY"
    "DIFY_SANDBOX_API_KEY"
    "EVOLUTION_AUTHENTICATION_API_KEY"
    "HANDOFF_SHARED_SECRET"
    "GRAFANA_ADMIN_PASSWORD"
    "CLOUDFLARE_API_TOKEN"
)

echo "Fetching secrets from GCP Secret Manager..."

# Start with a fresh temp file
echo "# Generated by scripts/sync-secrets-gcp.sh" > "$TEMP_FILE"

for secret in "${SECRETS[@]}"; do
    echo "Syncing $secret..."
    value=$(gcloud secrets versions access latest --secret="$secret" 2>/dev/null)
    if [ $? -eq 0 ]; then
        echo "$secret=$value" >> "$TEMP_FILE"
    else
        echo "Warning: Failed to fetch $secret. Is it created in GCP?"
    fi
done

# Check if we should merge with existing .env
if [ -f "$OUTPUT_FILE" ]; then
    # Merge: Update matching keys and add new ones
    # For now, let's keep it simple and just overwrite or inform
    echo "Updating $OUTPUT_FILE..."
    # (Simplified: overwriting with fetched values)
    cp "$TEMP_FILE" "$OUTPUT_FILE"
else
    mv "$TEMP_FILE" "$OUTPUT_FILE"
fi

rm -f "$TEMP_FILE"
echo "Sync complete."
